server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb+srv://bootcam:akOU0Wt6DZbORQrD@cluster0.o44govo.mongodb.net/bootcam?retryWrites=true&w=majority
    mongodbkafka:
      uri: mongodb+srv://usermensaje:3aUsSD74IsQsa4LB@clusterkafka.aycs0q6.mongodb.net/mensajeria?retryWrites=true&w=majority

  kafka:
    consumer:
      group-id: my-group
      bootstrap-servers: localhost:9092
    producer:
      properties:
          spring:
             json:
                trusted:
                    packages=com.nttdata.bootcam.banca.consulta.producto.infrastructure.event

                         
springdoc:
    api-docs:
      groups:
        enabled: true
      path: /swagger-doc/v3/api-docs
    swagger-ui:
      path: /swagger-doc/swagger-ui.html
      
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      
resilience4j:
  circuitbreaker:
    instances:
        accountService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      accountService:
          maxRetryAttempts: 5
          waitDuration: 10s
      
      
        